### Create User (works as-is, just remove nested arrays)
POST http://localhost:8081/api/user
Content-Type: application/json

{
  "fullName": "Jakub Kowalski",
  "email": "",
  "password": "",
  "role": ""
}

### Create Rank "Przewodnik" (requirements will be created separately)
POST http://localhost:8081/api/rank
Content-Type: application/json

{
  "fullName": "Przewodnik",
  "shortName": "pwd",
  "idea": "Swoją postawą propaguje harcerski system wartości wynikający z Przyrzeczenia i Prawa Harcerskiego. Poznaje siebie i motywy swojego postępowania. Pracuje nad własnymi słabościami i rozwija zdolności. Jest wzorem dla harcerzy. We współdziałaniu z dziećmi i młodzieżą znajduje radość, umie być starszym kolegą i przewodnikiem. Bierze aktywny udział w życiu drużyny, świadomie stosując metodę harcerską i wykorzystując przykład osobisty do realizacji celów wychowawczych. Ma poczucie odpowiedzialności za pracę i powierzoną grupę. Współtworzy hufcową wspólnotę. Ma świadomość wychowawczej roli służby w harcerstwie.",
  "startRequirements": [
    "Złożenie Przyrzeczenia Harcerskiego",
    "Przedstawienie KSI programu swojej próby, zapewniającego realizację wymagań",
    "Ukończone 16 lat"
  ],
  "endRequirements": [
    "Osiągnięcie poziomu opisanego w idei stopnia i zrealizowanie wymagań próby",
    "Przestrzeganie zasad „Polityki ochrony bezpieczeństwa dzieci w ZHP oraz innych przepisów dotyczących zasad bezpieczeństwa w pracy z dziećmi i młodzieżą",
    "Posiadanie wiedzy i umiejętności na poziomie stopnia harcerki orlej – harcerza orlego",
    "Ukończenie minimum 15-godzinnego kursu pierwszej pomocy zawierającego zajęcia w praktyce",
    "Pozytywnie oceniona służba w gromadzie/drużynie w okresie realizacji próby",
    "Ukończenie kursu przewodnikowskiego",
    "Posiadanie wiedzy i umiejętności odpowiadających wymaganiom stawianym wychowawcom wypoczynku"
  ]
}

### Create Requirements for Rank ID 1 (assuming the rank above got ID 1)
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "1",
  "content": "Kształtuje własną osobowość zgodnie z Prawem Harcerskim, w tym ułożył i konsekwentnie realizował plan swojego rozwoju.",
  "rankId": 1
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "2",
  "content": "Pogłębia swoją wiedzę i rozwija swoje zainteresowania.",
  "rankId": 1
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "3",
  "content": "Zachowuje właściwe proporcje w wypełnianiu obowiązków wynikających z przynależności do różnych grup społecznych (rodzina, szkoła, drużyna, środowisko zawodowe).",
  "rankId": 1
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "4",
  "content": "Podejmuje stałą służbę w swoim harcerskim środowisku.",
  "rankId": 1
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "5",
  "content": "Bierze udział w życiu hufca.",
  "rankId": 1
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "6",
  "content": "W trakcie minimum 9-miesięcznej aktywnej służby w gromadzie/drużynie wykazał się umiejętnością pracy wychowawczej metodą harcerską z dziećmi lub młodzieżą w wybranej grupie wiekowej,",
  "rankId": 1
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "6.1",
  "content": "w tym umiejętnościami: stosowania instrumentów metodycznych,",
  "rankId": 1
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "6.2",
  "content": "w tym umiejętnościami: stosowania systemu małych grup,",
  "rankId": 1
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "6.3",
  "content": "w tym umiejętnościami: tworzenia programu gromady/drużyny, jego realizacji i podsumowania,",
  "rankId": 1
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "6.4",
  "content": "w tym umiejętnościami: pracy z Prawem i Przyrzeczeniem / Prawem i Obietnicą,",
  "rankId": 1
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "6.5",
  "content": "w tym umiejętnościami: samodzielnego prowadzenia zbiórek",
  "rankId": 1
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "6.6",
  "content": "oraz uczestniczył w: organizacji wyjazdowych form pracy wykorzystujących kontakt z przyrodą,",
  "rankId": 1
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "6.7",
  "content": "oraz uczestniczył w: organizowaniu oraz przeprowadzeniu gier i form pracy w terenie uwzględniających współdziałanie i współzawodnictwo,",
  "rankId": 1
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "6.8",
  "content": "oraz uczestniczył w: pozyskiwaniu środków finansowych lub innych form wsparcia działalności gromady/drużyny,",
  "rankId": 1
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "6.9",
  "content": "oraz uczestniczył w: organizacji obozu (kolonii) lub zimowiska drużyny/gromady i pełnił na nim funkcję,",
  "rankId": 1
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "6.10",
  "content": "oraz uczestniczył w: prowadzeniu dokumentacji niezbędnej do działania gromady/drużyny,",
  "rankId": 1
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "6.11",
  "content": "oraz uczestniczył w: współpracy ze środowiskiem działania – rodzicami, szkołą itp.",
  "rankId": 1
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "7",
  "content": "Wykazał się umiejętnością stosowania zasad dotyczących umundurowania, musztry, ceremoniału harcerskiego w pracy z drużyną.",
  "rankId": 1
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "8",
  "content": "Wiedzę zdobytą w harcerskiej literaturze i mediach wykorzystał w pracy wychowawczej. Przeczytał minimum 3 książki harcerskie.",
  "rankId": 1
}

### Create Rank "Podharcmistrz" 
POST http://localhost:8081/api/rank
Content-Type: application/json

{
  "fullName": "Podharcmistrz",
  "shortName": "phm",
  "idea": "Określa kierunki swojego rozwoju i je realizuje. Pracuje nad własnymi słabościami, przełamując je. Przykładem osobistym świadomie i pozytywnie oddziałuje na otoczenie. Rozumie ludzi i otaczającą go rzeczywistość – reaguje na ich potrzeby. Systematycznie stosuje służbę jako narzędzie harcerskiej pracy wychowawczej. Potrafi zauważyć sytuacje problemowe i je rozwiązywać. Umie spojrzeć na nie szerzej, niż tylko z perspektywy własnego środowiska. Buduje swój autorytet. Doskonali swą wiedzę i umiejętności wychowawcze. Dzieli się nimi z kadrą. Świadomie i konsekwentnie stosuje metodę harcerską. Pracuje w zespole instruktorskim. Ma własny pogląd na sprawy nurtujące jego środowisko harcerskie. Wzmacnia tożsamość harcerstwa.",
  "startRequirements": [
    "Pozytywnie oceniona praca instruktorska przez co najmniej 12 miesięcy od przyznania stopnia przewodnika.",
    "Zaliczona służba instruktorska.",
    "Ukończone 18 lat.",
    "Przedstawienie KSI programu swojej próby zapewniającego realizację wymagań.",
    "Brał udział w doskonaleniu zastępowych, przybocznych.",
    "Ma doświadczenie na funkcji drużynowego lub przybocznego."
  ],
  "endRequirements": [
    "Osiągnięcie poziomu opisanego w idei stopnia i zrealizowanie wymagań próby.",
    "Pozytywnie oceniona praca instruktorska w okresie realizacji próby.",
    "Ukończenie kursu podharcmistrzowskiego."
  ]
}

### Create Requirements for Rank ID 2 (assuming Podharcmistrz got ID 2)
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "1",
  "content": "Wykazał się umiejętnością pracy nad sobą, stawiania celów w życiu, podejmowania działań (do ich realizacji), ich oceny i wyciągania wniosków.",
  "rankId": 2
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "2",
  "content": "Podnosi swoje umiejętności i kwalifikacje.",
  "rankId": 2
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "3",
  "content": "Bierze czynny udział w życiu otaczającego go środowiska społecznego.",
  "rankId": 2
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "4",
  "content": "W swojej pracy instruktorskiej świadomie wykorzystuje służbę.",
  "rankId": 2
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "5",
  "content": "Wykazał się umiejętnością pracy w zespole, komunikowania się oraz motywowania innych. Zrealizował zadanie instruktorskie na poziomie szczepu lub hufca.",
  "rankId": 2
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "6",
  "content": "Pogłębił znajomość harcerskiego systemu wychowawczego oraz zasad metodyki grup wiekowych.",
  "rankId": 2
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "7",
  "content": "Stosuje metodę harcerską w pracy z instruktorami.",
  "rankId": 2
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "8",
  "content": "Świadomie stosuje System pracy z kadrą.",
  "rankId": 2
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "9",
  "content": "Pracuje nad swoją postawą instruktorską. Doskonali swoje umiejętności harcerskie i instruktorskie – w trakcie próby brał udział w minimum 2 wybranych formach kształceniowych.",
  "rankId": 2
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "10",
  "content": "Przygotował się do roli opiekuna próby na stopnie instruktorskie.",
  "rankId": 2
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "11",
  "content": "Pozyskał sojuszników do działalności harcerskiej.",
  "rankId": 2
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "12",
  "content": "Pełnił funkcję instruktorską w czasie roku harcerskiego i był członkiem komendy kolonii/obozu lub zimowiska.",
  "rankId": 2
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "13",
  "content": "Orientuje się w historii i aktualnej sytuacji harcerstwa. Korzysta z harcerskiej literatury i mediów. Przeczytał minimum 3 wybrane książki harcerskie.",
  "rankId": 2
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "14",
  "content": "Wykazał się znajomością przepisów finansowych i organizacyjnych oraz zasad prowadzenia obozu harcerskiego odpowiadających wymaganiom stawianym kierownikom wypoczynku.",
  "rankId": 2
}

###
POST http://localhost:8081/api/requirement
Content-Type: application/json

{
  "number": "15",
  "content": "Wykazał się umiejętnością pozyskiwania środków na działalność harcerską.",
  "rankId": 2
}

### Create RankInProgress (using IDs instead of nested objects)
POST http://localhost:8081/api/rankInProgress
Content-Type: application/json

{
  "rankId": 1,
  "userId": 1,
  "mentorId": 1,
  "status": "CREATED"
}


### Generate RankInProgress for User ID 1 and Rank ID 1
GET http://localhost:8081/api/rankInProgress/generate/1
